name: Release mods

on:
  push:
    tags:
      - "*-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifacts
        run: |
          mkdir -p artifacts

          TAG_NAME=${{ github.ref_name }}
          MOD_ID=${TAG_NAME%-*}
          VERSION=${TAG_NAME##*-}
          MOD_FOLDER=$(dirname "$(grep -rl "\"ModID\": \"${MOD_ID//-/_}\"" --include="modinfo.json")")

          zip -r "artifacts/${MOD_FOLDER##*/}-${VERSION}.zip" "${MOD_FOLDER}"

      - name: Attach artifacts to release
        uses: actions/upload-artifact@v4
        with:
          name: mod-artifacts
          path: artifacts/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
