name: Release mod

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref }}
        title: Release ${{ github.ref }}
        prerelease: false

    - name: Create the folder structure and zip contents
      run: |
        git ls-tree --name-only HEAD | grep -v '^\.git' | xargs -I {} cp -r {} "${MOD_NAME}/"
        zip -r "${{ env.MOD_NAME }}.zip" "${{ env.MOD_NAME }}"

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MOD_NAME }}
        path: "${{ env.MOD_NAME }}.zip"
